### ISSUE TITLE
adjacent_join not exported

### ISSUE THREAD

**Issue by ginolhac** [dgrtwo/adventdrob#1]
Hi David,

### Acknowledgements part

not really an issue, it is mostly an excuse to thank you warmly for setting up this package, posting your amazing solutions on twitter and highlighting the key parts!

So elegant, full of wise and knowledge, I really appreciate your work (for quite some years now, never forgot the Brauer series on your blog).

### Issue part

The function `advent_join()` is not exported now, only `advent_nest()`. Of course, still available:

```r
adventdrob:::adjacent_join(x)
# A tibble: 360 × 6
     row value   col  row2  col2 value2
   <int> <dbl> <int> <dbl> <dbl>  <dbl>
 1     1     1    10     1     9      2
 2     1     1    10     2    10      1
 3     1     2     9     1     8      3
 4     1     2     9     1    10      1
[...]
````

But you might want want to export it for consistency.

Best wishes

<details>

`renv` entry:

```
    "adventdrob": {
      "Package": "adventdrob",
      "Version": "0.0.1",
      "Source": "GitHub",
      "RemoteType": "github",
      "RemoteHost": "api.github.com",
      "RemoteUsername": "dgrtwo",
      "RemoteRepo": "adventdrob",
      "RemoteRef": "main",
      "RemoteSha": "db9dfb198cebfe1bd578fdbb0135a4925f0e3977",
      "Hash": "7a4df00f294d1337e601cc215fa8a73b"
    }
```
</details>

**Comment by dgrtwo** [comment]
Good catch- thanks for your kind note!
